spring:
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : ${DEFAULT_ZONE}
  instance:
    hostname: ${EUREKA_HOST_NAME}

