spring:
  zipkin:
    base-url: http://zipkin.default.svc.cluster.local:9411

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://EUREKA-CLUSTER

