spring:
  boot:
    admin:
      client:
        url: ${SPRING_ADMIN_SERVER_URL:http://localhost:8093}
        username: "admin"
        password: "admin"
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}
  

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      
logging:
  file:
    name: application.log
    max-size: 20MB
    max-history: 20
  
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
