spring:
  boot:
    admin:
      client:
        url: http://spring-admin.default.svc.cluster.local:8093
        username: "admin"
        password: "admin"
  zipkin:
    base-url: http://zipkin.default.svc.cluster.local:9411
  

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      
logging:
  file:
    name: application.log
    max-size: 20MB
    max-history: 20
  
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
